Document: genlpacket
Title: Debian genlpacket Manual
Author: <insert document author here>
Abstract: This manual describes what genlpacket is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/genlpacket/genlpacket.sgml.gz

Format: postscript
Files: /usr/share/doc/genlpacket/genlpacket.ps.gz

Format: text
Files: /usr/share/doc/genlpacket/genlpacket.text.gz

Format: HTML
Index: /usr/share/doc/genlpacket/html/index.html
Files: /usr/share/doc/genlpacket/html/*.html
